// <auto-generated />
namespace OnlineShopMvcWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditTableCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTableCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201812080442086_Edit-Table-Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
